require "sairu.config.launch"
require "sairu.config.options"
require "sairu.config.keymaps"
require "sairu.config.autocmds"
spec "sairu.plugins.colorscheme"
-- spec "sairu.plugins.devicons"
-- spec "sairu.plugins.treesitter"
-- spec "sairu.plugins.mason"
-- spec "sairu.plugins.schemastore"
-- spec "sairu.plugins.lspconfig"
-- spec "sairu.plugins.cmp"
-- spec "sairu.plugins.telescope"
-- spec "sairu.plugins.none-ls"
-- spec "sairu.plugins.illuminate"
-- spec "sairu.plugins.gitsigns"
-- spec "sairu.plugins.whichkey"
-- spec "sairu.plugins.nvimtree"
-- spec "sairu.plugins.comment"
-- spec "sairu.plugins.lualine"
-- spec "sairu.plugins.navic"
-- spec "sairu.plugins.breadcrumbs"'
-- spec "sairu.plugins.harpoon"
-- spec "sairu.plugins.neotest"
-- spec "sairu.plugins.autopairs"
-- spec "sairu.plugins.neogit"
-- spec "sairu.plugins.alpha"
-- spec "sairu.plugins.project"
-- spec "sairu.plugins.indentline"
-- spec "sairu.plugins.toggleterm"
require "sairu.lazy"
