context.objects = [
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "Discord"
            node.description = "Discord Audio"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
            object.linger    = 1
        }
    }
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "Game"
            node.description = "Game Audio"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
            object.linger    = 1
        }
    }
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "Music"
            node.description = "Music Audio"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
            object.linger    = 1
        }
    }
]
