local M = {}

function M.get(c, cfg)
  local it = cfg.italics

  return {
    ColorColumn = { bg = c.line },
    Conceal = { fg = c.fg_dark },
    CursorLine = { bg = c.line },
    CursorLineNr = { fg = c.blue, bold = true },
    CursorColumn = { bg = c.line },
    Directory = { fg = c.blue },
    EndOfBuffer = { fg = c.bg_dark },
    FloatBorder = { fg = c.border, bg = c.bg_float },
    FloatTitle = { fg = c.cyan, bg = c.bg_float, bold = true },
    FoldColumn = { fg = c.fg_gutter, bg = c.bg },
    Folded = { fg = c.fg_dark, bg = c.bg_dark },
    LineNr = { fg = c.fg_gutter },
    MatchParen = { fg = c.yellow, bold = true },
    Normal = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_float },
    NormalNC = { fg = c.fg, bg = cfg.dim_inactive and c.bg_dark or c.bg },
    Pmenu = { fg = c.fg, bg = c.bg_dark },
    PmenuSel = { fg = c.fg, bg = c.selection, bold = true },
    PmenuSbar = { bg = c.bg_float },
    PmenuThumb = { bg = c.border },
    Search = { fg = c.bg, bg = c.yellow, bold = true },
    IncSearch = { fg = c.bg, bg = c.orange, bold = true },
    SignColumn = { fg = c.fg_dark, bg = c.bg },
    StatusLine = { fg = c.fg, bg = c.bg_dark },
    StatusLineNC = { fg = c.fg_dark, bg = c.bg_dark },
    TabLine = { fg = c.fg_dark, bg = c.bg_dark },
    TabLineFill = { fg = c.fg_dark, bg = c.bg },
    TabLineSel = { fg = c.fg, bg = c.bg_float, bold = true },
    Title = { fg = c.blue, bold = true },
    VertSplit = { fg = c.border },
    Visual = { bg = c.selection },
    WinSeparator = { fg = c.border },

    Comment = { fg = c.fg_dark, italic = it.comments },
    Constant = { fg = c.orange },
    String = { fg = c.green, italic = it.strings },
    Character = { fg = c.green, italic = it.strings },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Float = { fg = c.orange },

    Identifier = { fg = c.fg, italic = it.variables },
    Function = { fg = c.blue, italic = it.functions },

    Statement = { fg = c.magenta, italic = it.keywords },
    Conditional = { fg = c.magenta, italic = it.keywords },
    Repeat = { fg = c.magenta, italic = it.keywords },
    Label = { fg = c.magenta, italic = it.keywords },
    Operator = { fg = c.cyan },
    Keyword = { fg = c.magenta, italic = it.keywords },
    Exception = { fg = c.red, italic = it.keywords },

    PreProc = { fg = c.yellow },
    Include = { fg = c.magenta, italic = it.keywords },
    Define = { fg = c.magenta, italic = it.keywords },
    Macro = { fg = c.yellow },
    PreCondit = { fg = c.yellow },

    Type = { fg = c.cyan, italic = it.types },
    StorageClass = { fg = c.cyan, italic = it.types },
    Structure = { fg = c.cyan, italic = it.types },
    Typedef = { fg = c.cyan, italic = it.types },

    Special = { fg = c.red },
    SpecialComment = { fg = c.fg_dark, italic = true },
    Error = { fg = c.error, bold = true },
    Todo = { fg = c.yellow, bold = true },

    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },

    LspReferenceText = { bg = c.line },
    LspReferenceRead = { bg = c.line },
    LspReferenceWrite = { bg = c.line },

    ["@comment"] = { link = "Comment" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.magenta, italic = it.keywords },
    ["@string"] = { link = "String" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@function"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@constructor"] = { fg = c.blue },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.cyan, italic = true },
    ["@property"] = { fg = c.fg },
    ["@variable"] = { fg = c.fg, italic = it.variables },
    ["@variable.builtin"] = { fg = c.red, italic = true },
    ["@constant"] = { link = "Constant" },
    ["@module"] = { fg = c.cyan },

    TelescopeNormal = { fg = c.fg, bg = c.bg_float },
    TelescopeBorder = { fg = c.border, bg = c.bg_float },
    TelescopePromptNormal = { fg = c.fg, bg = c.bg_dark },
    TelescopePromptBorder = { fg = c.border, bg = c.bg_dark },
    TelescopePromptTitle = { fg = c.bg, bg = c.blue, bold = true },
    TelescopePreviewTitle = { fg = c.bg, bg = c.magenta, bold = true },
    TelescopeResultsTitle = { fg = c.bg, bg = c.cyan, bold = true },
    TelescopeSelection = { bg = c.line, bold = true },
    TelescopeMatching = { fg = c.blue, bold = true },

    BlinkCmpMenu = { fg = c.fg, bg = c.bg_dark },
    BlinkCmpMenuBorder = { fg = c.border, bg = c.bg_dark },
    BlinkCmpMenuSelection = { fg = c.fg, bg = c.bg_float, bold = true },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelMatch = { fg = c.blue, bold = true },
    BlinkCmpLabelDetail = { fg = c.fg_dark },
    BlinkCmpLabelDescription = { fg = c.fg_dark },
    BlinkCmpSource = { fg = c.cyan, italic = true },
    BlinkCmpKind = { fg = c.magenta },
    BlinkCmpDoc = { fg = c.fg, bg = c.bg_float },
    BlinkCmpDocBorder = { fg = c.border, bg = c.bg_float },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_float },
    BlinkCmpSignatureHelpBorder = { fg = c.border, bg = c.bg_float },

    TroubleNormal = { fg = c.fg, bg = c.bg_float },
    TroubleNormalNC = { fg = c.fg, bg = c.bg_float },
    TroublePreview = { fg = c.fg, bg = c.bg_dark },
    TroubleIndent = { fg = c.border },
    TroubleText = { fg = c.fg },
    TroubleCount = { fg = c.bg, bg = c.magenta, bold = true },
    TroubleIconArray = { fg = c.orange },
    TroubleIconBoolean = { fg = c.orange },
    TroubleIconClass = { fg = c.cyan },
    TroubleIconConstant = { fg = c.orange },
    TroubleIconConstructor = { fg = c.blue },
    TroubleIconEnum = { fg = c.cyan },
    TroubleIconEnumMember = { fg = c.orange },
    TroubleIconEvent = { fg = c.red },
    TroubleIconField = { fg = c.fg },
    TroubleIconFile = { fg = c.blue },
    TroubleIconFunction = { fg = c.blue },
    TroubleIconInterface = { fg = c.cyan },
    TroubleIconMethod = { fg = c.blue },
    TroubleIconModule = { fg = c.cyan },
    TroubleIconNamespace = { fg = c.cyan },
    TroubleIconNull = { fg = c.fg_dark },
    TroubleIconNumber = { fg = c.orange },
    TroubleIconObject = { fg = c.cyan },
    TroubleIconOperator = { fg = c.cyan },
    TroubleIconPackage = { fg = c.cyan },
    TroubleIconProperty = { fg = c.fg },
    TroubleIconString = { fg = c.green },
    TroubleIconStruct = { fg = c.cyan },
    TroubleIconTypeParameter = { fg = c.cyan },
    TroubleIconVariable = { fg = c.fg },
  }
end

return M
