return {
	Array = " ",
	Boolean = " ",
	Class = " ",
	Color = " ",
	Constant = " ",
	Constructor = " ",
	Enum = " ",
	EnumMember = " ",
	Event = " ",
	Field = " ",
	File = " ",
	Folder = "󰉋 ",
	Function = " ",
	Interface = " ",
	Key = " ",
	Keyword = " ",
	Method = " ",
	Module = " ",
	Namespace = " ",
	Null = "󰟢 ",
	Number = " ",
	Object = " ",
	Operator = " ",
	Package = " ",
	Property = " ",
	Reference = " ",
	Snippet = " ",
	String = " ",
	Struct = " ",
	Text = " ",
	TypeParameter = " ",
	Unit = " ",
	Value = " ",
	Variable = " ",
	LineAdded = " ",
	LineModified = " ",
	LineRemoved = " ",
	FileDeleted = " ",
	FileIgnored = "◌",
	FileRenamed = " ",
	FileStaged = "S",
	FileUnmerged = "",
	FileUnstaged = "",
	FileUntracked = "U",
	Diff = " ",
	Repo = " ",
	Octoface = " ",
	Copilot = " ",
	Branch = "",
	ArrowCircleDown = "",
	ArrowCircleLeft = "",
	ArrowCircleRight = "",
	ArrowCircleUp = "",
	BoldArrowDown = "",
	BoldArrowLeft = "",
	BoldArrowRight = "",
	BoldArrowUp = "",
	BoldClose = "",
	BoldDividerLeft = "",
	BoldDividerRight = "",
	BoldLineLeft = "▎",
	BoldLineMiddle = "┃",
	BoldLineDashedMiddle = "┋",
	BookMark = "",
	BoxChecked = " ",
	Bug = " ",
	Stacks = "",
	Scopes = "",
	Watches = "󰂥",
	DebugConsole = " ",
	Calendar = " ",
	Check = "",
	ChevronRight = "",
	ChevronShortDown = "",
	ChevronShortLeft = "",
	ChevronShortRight = "",
	ChevronShortUp = "",
	Circle = " ",
	Close = "󰅖",
	CloudDownload = " ",
	Code = "",
	Comment = "",
	Dashboard = "",
	DividerLeft = "",
	DividerRight = "",
	DoubleChevronRight = "»",
	Ellipsis = "",
	EmptyFolder = " ",
	EmptyFolderOpen = " ",
	File = " ",
	FileSymlink = "",
	Files = " ",
	FindFile = "󰈞",
	FindText = "󰊄",
	Fire = "",
	Folder = "󰉋 ",
	FolderOpen = " ",
	FolderSymlink = " ",
	Forward = " ",
	Gear = " ",
	History = " ",
	Lightbulb = " ",
	LineLeft = "▏",
	LineMiddle = "│",
	List = " ",
	Lock = " ",
	NewFile = " ",
	Note = " ",
	Package = " ",
	Pencil = "󰏫 ",
	Plus = " ",
	Project = " ",
	Search = " ",
	SignIn = " ",
	SignOut = " ",
	Tab = "󰌒 ",
	Table = " ",
	Target = "󰀘 ",
	Telescope = " ",
	Text = " ",
	Tree = "",
	Triangle = "󰐊",
	TriangleShortArrowDown = "",
	TriangleShortArrowLeft = "",
	TriangleShortArrowRight = "",
	TriangleShortArrowUp = "",
	BoldError = "",
	Error = "",
	BoldWarning = "",
	Warning = "",
	BoldInformation = "",
	Information = "",
	BoldQuestion = "",
	Question = "",
	BoldHint = "",
	Hint = "󰌶",
	Debug = "",
	Trace = "✎",

	Robot = "󰚩 ",
	Squirrel = " ",
	Tag = " ",
	Watch = "",
	Smiley = " ",
	Package = " ",
	CircuitBoard = " ",

	javascript = " ", -- JavaScript
	java = " ", -- Java
	typescript = "󰛦 ", -- TypeScript
	python = "🐍 ", -- Python
	go = " ", -- Go
	php = " ", -- PHP
	c = " ", -- C
	cpp = " ", -- C++
	html = " ", -- HTML
	css = " ", -- CSS
	ruby = " ", -- Ruby
	go = " ", -- Go
	php = " ", -- PHP
	kotlin = " ", -- Kotlin
	swift = "󰈚 ", -- Swift
	dart = " ", -- Dart
	lua = " ", -- Lua
	scala = " ", -- Scala
	elixir = " ", -- Elixir
	haskell = " ", -- Haskell
	sql = " ", -- SQL
	powershell = "󰜢 ", -- PowerShell
	shell = " ", -- Shell
	assembly = " ", -- Assembly
	vim = " ", -- Vim Script
	markdown = " ", -- Markdown
	json = " ", -- JSON
	yaml = " ", -- YAML
	xml = "謹 ", -- XML
	toml = " ", -- TOML
	dockerfile = "󰡨 ", -- Dockerfile
	makefile = " ", -- Makefile
	cs = " ", -- C#
	tsx = "jsx", -- TypeScript JSX
	jsx = " ", -- JavaScript JSX
	html = " ", -- HTML
	css = " ", -- CSS
	graphql = " ", -- GraphQL
	git = " ", -- Git
	lua = " ", -- Lua
	php = " ", -- PHP
	ruby = " ", -- Ruby
	swift = "ﯟ ", -- Swift
	kotlin = "󱈙 ", -- Kotlin
	rust = " ", -- Rust
	go = " ", -- Go
	scala = " ", -- Scala
	elixir = " ", -- Elixir
	haskell = " ", -- Haskell
}
