foreground #D7E2F0
background #0A0E14
selection_foreground #F2F7FF
selection_background #1E2D40
cursor #FFD000
active_border_color #A77DFF
inactive_border_color #1E2D40
bell_border_color #FF3B5C

# ANSI Colors
color0  #0A0E14
color1  #FF3B5C
color2  #39FF14
color3  #FFD000
color4  #2AC3FF
color5  #A77DFF
color6  #56D4DD
color7  #D7E2F0

color8  #4B5D78
color9  #FF6B81
color10 #9AF5A3
color11 #FFE45E
color12 #6AD7FF
color13 #C7A3FF
color14 #7BE7EE
color15 #F2F7FF
