return {
  -- Blackout Gotham baseline: Carbonfox gives graphite/black without neon wash.
  {
    "EdenEast/nightfox.nvim",
    enabled = true,
    lazy = false,
    priority = 1000,
    opts = {
      options = {
        transparent = false,
        terminal_colors = true,
        styles = {
          comments = "italic",
          conditionals = "italic",
          constants = "NONE",
          functions = "bold",
          keywords = "NONE",
          operators = "NONE",
          strings = "NONE",
          types = "bold",
          variables = "NONE",
        },
      },
      palettes = {
        carbonfox = {
          bg0 = "#0b0b0d",
          bg1 = "#111113",
          bg2 = "#161616",
          bg3 = "#1f1f1f",
          bg4 = "#262626",
          fg1 = "#d7d7d7",
          fg2 = "#b0b0b0",
          fg3 = "#787878",
          sel0 = "#262626",
          sel1 = "#303030",
          comment = "#5f5f5f",
          yellow = "#c8a43a",
        },
      },
      specs = {
        carbonfox = {
          syntax = {
            keyword = "#ffcc4d",
            func = "#f2f7ff",
            string = "#a6e36f",
            type = "#b69cff",
            variable = "#d0d0c8",
            const = "#ffd36e",
            operator = "#9aa0a6",
            comment = "#686868",
          },
          diag = {
            ok = "#787878",
            warn = "#c8a43a",
          },
        },
      },
      groups = {
        carbonfox = {
          CursorLineNr = { fg = "#ffcc4d", style = "bold" },
          FloatBorder = { fg = "#393939", bg = "#111113" },
          NormalFloat = { bg = "#111113" },
          WinSeparator = { fg = "#262626" },

          -- Snacks explorer/sidebar: explicit Gotham hierarchy.
          -- Without this, folder names inherit `Directory` from Carbonfox and read
          -- almost white, which makes the file tree look flat and noisy.
          Directory = { fg = "#38c7ff", style = "bold" },
          CursorLine = { bg = "#1a1a1a" },
          Visual = { bg = "#262626" },
          LineNr = { fg = "#4a4a4a" },
          SignColumn = { bg = "#0b0b0d" },
          SnacksPicker = { fg = "#d0d0c8", bg = "#0b0b0d" },
          SnacksPickerList = { fg = "#d0d0c8", bg = "#0b0b0d" },
          SnacksPickerInput = { fg = "#d0d0c8", bg = "#111113" },
          SnacksPickerPreview = { fg = "#d0d0c8", bg = "#0b0b0d" },
          SnacksPickerBorder = { fg = "#303030", bg = "#0b0b0d" },
          SnacksPickerTitle = { fg = "#ffcc4d", bg = "#0b0b0d", style = "bold" },
          SnacksPickerListCursorLine = { bg = "#1a1a1a" },
          SnacksPickerCursorLine = { bg = "#1a1a1a" },
          SnacksPickerDir = { fg = "#38c7ff", style = "bold" },
          SnacksPickerFile = { fg = "#d0d0c8" },
          SnacksPickerPathHidden = { fg = "#525252" },
          SnacksPickerPathIgnored = { fg = "#464646" },
          SnacksPickerGitStatusUntracked = { fg = "#8a936a" },
          SnacksPickerGitStatusModified = { fg = "#ffcc4d" },
          SnacksPickerGitStatusDeleted = { fg = "#8a5f5f" },
          SnacksPickerMatch = { fg = "#fff07a", style = "bold" },
          SnacksPickerIcon = { fg = "#38c7ff" },
          SnacksPickerIconDirectory = { fg = "#38c7ff" },
          SnacksPickerDimmed = { fg = "#686868" },
          SnacksPickerDelim = { fg = "#525252" },
          SnacksPickerToggle = { fg = "#ffcc4d" },
          SnacksExplorerNormal = { fg = "#d0d0c8", bg = "#0b0b0d" },
          SnacksExplorerDir = { fg = "#38c7ff", style = "bold" },
          SnacksExplorerFile = { fg = "#d0d0c8" },
          SnacksExplorerGitStatusUntracked = { fg = "#8a936a" },
          SnacksExplorerGitStatusModified = { fg = "#ffcc4d" },
          SnacksExplorerGitStatusDeleted = { fg = "#8a5f5f" },
          EdgyNormal = { fg = "#d0d0c8", bg = "#0b0b0d" },
          EdgyTitle = { fg = "#ffcc4d", bg = "#0b0b0d", style = "bold" },
          EdgyWinBar = { fg = "#38c7ff", bg = "#111113", style = "bold" },
          EdgyWinBarNC = { fg = "#686868", bg = "#0b0b0d" },

          -- Syntax: still mostly monochrome, but readable by semantic role.
          -- The previous baseline made functions and variables nearly identical.
          Identifier = { fg = "#d0d0c8" },
          Function = { fg = "#f2f7ff", style = "bold" },
          Statement = { fg = "#ffcc4d" },
          Keyword = { fg = "#ffcc4d" },
          Conditional = { fg = "#ffcc4d", style = "italic" },
          Repeat = { fg = "#ffcc4d" },
          Type = { fg = "#b69cff", style = "bold" },
          String = { fg = "#a6e36f" },
          Constant = { fg = "#ffd36e" },
          Number = { fg = "#ffd36e" },
          Boolean = { fg = "#ffd36e", style = "bold" },
          Operator = { fg = "#9aa0a6" },
          Comment = { fg = "#686868", style = "italic" },
          ["@variable"] = { fg = "#d0d0c8" },
          ["@variable.builtin"] = { fg = "#ffcc4d", style = "italic" },
          ["@variable.parameter"] = { fg = "#78d6ff", style = "italic" },
          ["@parameter"] = { fg = "#78d6ff", style = "italic" },
          ["@variable.member"] = { fg = "#38c7ff" },
          ["@property"] = { fg = "#38c7ff" },
          ["@field"] = { fg = "#38c7ff" },
          ["@function"] = { fg = "#f2f7ff", style = "bold" },
          ["@function.call"] = { fg = "#f2f7ff", style = "bold" },
          ["@function.builtin"] = { fg = "#78d6ff", style = "bold" },
          ["@function.macro"] = { fg = "#ffcc4d", style = "bold" },
          ["@method"] = { fg = "#f2f7ff", style = "bold" },
          ["@method.call"] = { fg = "#f2f7ff", style = "bold" },
          ["@constructor"] = { fg = "#b69cff", style = "bold" },
          ["@type"] = { fg = "#b69cff", style = "bold" },
          ["@type.builtin"] = { fg = "#b69cff", style = "italic" },
          ["@module"] = { fg = "#78d6ff" },
          ["@namespace"] = { fg = "#78d6ff" },
          ["@keyword"] = { fg = "#ffcc4d" },
          ["@keyword.function"] = { fg = "#ffcc4d" },
          ["@keyword.conditional"] = { fg = "#ffcc4d", style = "italic" },
          ["@keyword.repeat"] = { fg = "#ffcc4d" },
          ["@keyword.import"] = { fg = "#ffcc4d", style = "italic" },
          ["@keyword.return"] = { fg = "#ffcc4d", style = "italic" },
          ["@keyword.operator"] = { fg = "#9aa0a6" },
          ["@string"] = { fg = "#a6e36f" },
          ["@string.special"] = { fg = "#78d6ff" },
          ["@number"] = { fg = "#ffd36e" },
          ["@boolean"] = { fg = "#ffd36e", style = "bold" },
          ["@constant"] = { fg = "#ffd36e" },
          ["@constant.builtin"] = { fg = "#ffd36e", style = "bold" },
          ["@operator"] = { fg = "#9aa0a6" },
          ["@comment"] = { fg = "#686868", style = "italic" },
          ["@tag"] = { fg = "#b69cff" },
          ["@tag.attribute"] = { fg = "#38c7ff", style = "italic" },
          ["@punctuation"] = { fg = "#9aa0a6" },

          -- LSP semantic tokens: these refine Treesitter when a language server is active.
          -- Keep roles visually distinct: params/hints italic, functions/types bold.
          ["@lsp.type.variable"] = { fg = "#d0d0c8" },
          ["@lsp.type.parameter"] = { fg = "#78d6ff", italic = true },
          ["@lsp.type.property"] = { fg = "#38c7ff" },
          ["@lsp.type.function"] = { fg = "#f2f7ff", bold = true },
          ["@lsp.type.method"] = { fg = "#f2f7ff", bold = true },
          ["@lsp.type.class"] = { fg = "#b69cff", bold = true },
          ["@lsp.type.interface"] = { fg = "#b69cff", italic = true },
          ["@lsp.type.type"] = { fg = "#b69cff", bold = true },
          ["@lsp.type.enum"] = { fg = "#b69cff", bold = true },
          ["@lsp.type.enumMember"] = { fg = "#ffd36e" },
          ["@lsp.type.namespace"] = { fg = "#78d6ff" },
          ["@lsp.type.decorator"] = { fg = "#ffcc4d", italic = true },
          ["@lsp.mod.readonly"] = { fg = "#ffd36e" },
          ["@lsp.mod.defaultLibrary"] = { fg = "#78d6ff", italic = true },
          LspInlayHint = { fg = "#5f7890", bg = "#111113", italic = true },

          DiagnosticVirtualTextError = { fg = "#8a5a5a", bg = "#111113" },
          DiagnosticVirtualTextWarn = { fg = "#ffcc4d", bg = "#111113" },
          DiagnosticVirtualTextInfo = { fg = "#787878", bg = "#111113" },
          DiagnosticVirtualTextHint = { fg = "#787878", bg = "#111113", style = "italic" },
          Search = { fg = "#161616", bg = "#ffcc4d", style = "bold" },
          IncSearch = { fg = "#161616", bg = "#fff07a", style = "bold" },
          NoiceCmdlinePopup = { fg = "#d7d7d7", bg = "#111113" },
          NoiceCmdlinePopupBorder = { fg = "#393939", bg = "#111113" },
          NoiceCmdlineIcon = { fg = "#ffcc4d", bg = "#111113", style = "bold" },
          NoiceMini = { fg = "#b0b0b0", bg = "#161616" },
          TroubleNormal = { fg = "#d7d7d7", bg = "#111113" },
          TroubleText = { fg = "#b0b0b0" },
          TroubleCount = { fg = "#ffcc4d", style = "bold" },
          TroublePreview = { bg = "#161616" },
          TinyInlineDiagnosticVirtualTextError = { fg = "#b86b6b", bg = "#111113" },
          TinyInlineDiagnosticVirtualTextWarn = { fg = "#ffcc4d", bg = "#111113" },
          TinyInlineDiagnosticVirtualTextInfo = { fg = "#787878", bg = "#111113" },
          TinyInlineDiagnosticVirtualTextHint = { fg = "#787878", bg = "#111113", style = "italic" },
        },
      },
    },
    config = function(_, opts)
      require("nightfox").setup(opts)
      vim.cmd.colorscheme("carbonfox")
    end,
  },

  { "folke/tokyonight.nvim", enabled = false },

  -- Alternate themes are kept available in history but disabled for v0 calm baseline.
  { "dupeiran001/nord.nvim", enabled = false },
  { "rose-pine/neovim", name = "rose-pine", enabled = false },
  { "catppuccin/nvim", name = "catppuccin", enabled = false },
  { "lifepillar/vim-gruvbox8", enabled = false },
  { "ellisonleao/gruvbox.nvim", enabled = false },
  { "rebelot/kanagawa.nvim", enabled = false },
  { "sainnhe/gruvbox-material", enabled = false },
  { "arcticicestudio/nord-vim", enabled = false },

  { "uloco/bluloco.nvim", enabled = false },
  { "scottmckendry/cyberdream.nvim", enabled = false },
  { "shatur/neovim-ayu", enabled = false },
  { "vimpostor/vim-lumen", enabled = false },
  { "rktjmp/lush.nvim", enabled = false },
}
